export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS products (
    id TEXT PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    category_slug TEXT NOT NULL,
    category_name TEXT NOT NULL,
    price_kurus INTEGER NOT NULL CHECK (price_kurus >= 0),
    color TEXT NOT NULL,
    image TEXT NOT NULL,
    image_position TEXT NOT NULL DEFAULT '50% 38%',
    description TEXT NOT NULL,
    material TEXT NOT NULL,
    fit TEXT NOT NULL,
    sizes_json TEXT NOT NULL,
    featured_rank INTEGER,
    status TEXT NOT NULL DEFAULT 'published' CHECK (status IN ('draft','published','archived')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_products_slug ON products(slug)`,
  `CREATE INDEX IF NOT EXISTS idx_products_category_status ON products(category_slug, status)`,
  `CREATE INDEX IF NOT EXISTS idx_products_featured ON products(featured_rank) WHERE status = 'published'`,
  `CREATE TABLE IF NOT EXISTS carts (
    id TEXT PRIMARY KEY,
    token_hash TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS cart_items (
    id TEXT PRIMARY KEY,
    cart_id TEXT NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
    product_id TEXT NOT NULL REFERENCES products(id),
    size TEXT NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0 AND quantity <= 10),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(cart_id, product_id, size)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_cart_items_cart_id ON cart_items(cart_id)`,
] as const;

export const initialCatalog = [
  {
    id: 'prd_simli_bustiyer',
    slug: 'simli-destekli-bustiyer-takim',
    name: 'Simli Destekli Büstiyer Takım',
    categorySlug: 'ic-giyim',
    categoryName: 'İç Giyim',
    priceKurus: 64627,
    color: 'Siyah',
    image: '/products/simli-bustiyer-takim.jpg',
    imagePosition: '50% 38%',
    description: 'Simli baskısı, balenli yapısı ve destekli formuyla güçlü görünümü rahatlıkla buluşturan iki parçalı takım.',
    material: 'Poliamid karışımı',
    fit: 'Balenli ve destekli',
    sizes: ['XS', 'S', 'M', 'L'],
    featuredRank: 1,
  },
  {
    id: 'prd_cizgili_dantel',
    slug: 'cizgili-dantelli-sutyen-takimi',
    name: 'Çizgili Dantelli Sütyen Takımı',
    categorySlug: 'ic-giyim',
    categoryName: 'İç Giyim',
    priceKurus: 66900,
    color: 'Pembe',
    image: '/products/cizgili-dantelli-takim.jpg',
    imagePosition: '50% 38%',
    description: 'Çizgili dokuyu ince dantel detaylarıyla birleştiren destekli sütyen takımı.',
    material: 'Dantel ve poliamid karışımı',
    fit: 'Destekli ve balenli',
    sizes: ['XS', 'S', 'M', 'L'],
    featuredRank: 2,
  },
  {
    id: 'prd_gri_crop',
    slug: 'fitilli-v-yaka-crop-bustiyer',
    name: 'Fitilli V Yaka Crop Büstiyer',
    categorySlug: 'crop-bustiyer',
    categoryName: 'Crop Büstiyer',
    priceKurus: 45900,
    color: 'Gri',
    image: '/products/gri-crop-bustiyer.jpg',
    imagePosition: '50% 35%',
    description: 'Fitilli dokusu, V yaka formu ve pedli yapısıyla gündelik stile uyum sağlayan crop büstiyer.',
    material: 'Esnek fitilli kumaş',
    fit: 'V yaka ve pedli',
    sizes: ['XS', 'S', 'M', 'L'],
    featuredRank: 3,
  },
  {
    id: 'prd_siyah_crop',
    slug: 'fitilli-u-yaka-siyah-crop',
    name: 'Fitilli U Yaka Siyah Crop',
    categorySlug: 'crop-bustiyer',
    categoryName: 'Crop Büstiyer',
    priceKurus: 45900,
    color: 'Siyah',
    image: '/products/crop-siyah-main.png',
    imagePosition: '50% 35%',
    description: 'Yumuşak fitilli dokusu ve vücudu saran U yaka formuyla denimden katmanlı kombinlere uzanan günlük siyah crop.',
    material: 'Esnek fitilli kumaş',
    fit: 'U yaka ve vücudu saran form',
    sizes: ['XS', 'S', 'M', 'L'],
    featuredRank: 4,
  },
  {
    id: 'prd_tul_babydoll',
    slug: 'dantelli-tul-babydoll-set',
    name: 'Dantelli Tül Babydoll Set',
    categorySlug: 'gecelik',
    categoryName: 'Gecelik',
    priceKurus: 69900,
    color: 'Pembe / Beyaz',
    image: '/products/tul-babydoll-set.jpg',
    imagePosition: '50% 38%',
    description: 'Hafif tül katmanları ve dantel detaylarıyla feminen bir gece görünümü sunan babydoll set.',
    material: 'Tül ve dantel karışımı',
    fit: 'Hafif ve akışkan',
    sizes: ['XS', 'S', 'M', 'L'],
    featuredRank: 5,
  },
] as const;
